// price feeds https://docs.chain.link/docs/binance-smart-chain-addresses/
const { getContractAddress, expandDecimals } = require("./helpers");

module.exports = {
  lineaTestnet: {
    // tokenWeight = 100,000
    btc: {
      name: "btc",
      address: getContractAddress("btc", true),
      priceFeed: getContractAddress("btcPriceFeed", true),
      decimals: 18,
      tokenIndex: 0,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 15000, // 15%
      minProfitBps: 0,
      maxUsdxAmount: 150 * 1000 * 1000,
      // bufferAmount: 450,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    eth: {
      name: "weth",
      address: getContractAddress("weth", true),
      priceFeed: getContractAddress("ethPriceFeed", true),
      decimals: 18,
      tokenIndex: 1,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 10000, // 10%
      minProfitBps: 0,
      maxUsdxAmount: 100 * 1000 * 1000,
      // bufferAmount: 15000,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    bnb: {
      name: "bnb",
      address: getContractAddress("bnb", true),
      priceFeed: getContractAddress("bnbPriceFeed", true),
      decimals: 18,
      tokenIndex: 2,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 10000, // 10%
      minProfitBps: 0,
      maxUsdxAmount: 100 * 1000 * 1000,
      // bufferAmount: 15000,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    busd: {
      name: "busd",
      address: getContractAddress("busd", true),
      priceFeed: getContractAddress("busdPriceFeed", true),
      decimals: 18,
      tokenIndex: 4,
      priceDecimals: 8,
      isStrictStable: true,
      tokenWeight: 35000, // 35%
      minProfitBps: 0,
      maxUsdxAmount: 350 * 1000 * 1000,
      // bufferAmount: 60 * 1000 * 1000,
      isStable: true,
      isShortable: false,
    },
    usdc: {
      name: "usdc",
      address: getContractAddress("usdc", true),
      decimals: 18,
      priceFeed: getContractAddress("usdcPriceFeed", true),
      priceDecimals: 8,
      isStrictStable: true,
      tokenWeight: 15000, // 15%
      minProfitBps: 0,
      maxUsdxAmount: 150 * 1000 * 1000,
      // bufferAmount: 60 * 1000 * 1000,
      isStable: true,
      isShortable: false
    },
    matic: {
      name: "matic",
      address: getContractAddress("matic", true),
      priceFeed: getContractAddress("maticPriceFeed", true),
      decimals: 18,
      tokenIndex: 1,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 5000, // 5%
      minProfitBps: 0,
      maxUsdxAmount: 50 * 1000 * 1000,
      // bufferAmount: 15000,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    op: {
      name: "op",
      address: getContractAddress("op", true),
      priceFeed: getContractAddress("opPriceFeed", true),
      decimals: 18,
      tokenIndex: 1,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 5000, // 5%
      minProfitBps: 0,
      maxUsdxAmount: 50 * 1000 * 1000,
      // bufferAmount: 15000,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    arb: {
      name: "arb",
      address: getContractAddress("arb", true),
      priceFeed: getContractAddress("arbPriceFeed", true),
      decimals: 18,
      tokenIndex: 1,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 5000, // 5%
      minProfitBps: 0,
      maxUsdxAmount: 50 * 1000 * 1000,
      // bufferAmount: 15000,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    nativeToken: {
      address: getContractAddress("weth"),
      decimals: 18,
      // priceDecimals: 8,
      isStrictStable: false,
    },
  },
  develop: {
    // tokenWeight = 100,000
    btc: {
      name: "btc",
      address: getContractAddress("btc", true),
      priceFeed: getContractAddress("btcPriceFeed", true),
      decimals: 18,
      tokenIndex: 0,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 15000, // 15%
      minProfitBps: 0,
      maxUsdxAmount: 150 * 1000 * 1000,
      // bufferAmount: 450,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    eth: {
      name: "weth",
      address: getContractAddress("weth", true),
      priceFeed: getContractAddress("ethPriceFeed", true),
      decimals: 18,
      tokenIndex: 1,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 10000, // 10%
      minProfitBps: 0,
      maxUsdxAmount: 100 * 1000 * 1000,
      // bufferAmount: 15000,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    bnb: {
      name: "bnb",
      address: getContractAddress("bnb", true),
      priceFeed: getContractAddress("bnbPriceFeed", true),
      decimals: 18,
      tokenIndex: 2,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 10000, // 10%
      minProfitBps: 0,
      maxUsdxAmount: 100 * 1000 * 1000,
      // bufferAmount: 15000,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    usdt: {
      name: "usdt",
      address: getContractAddress("usdt", true),
      priceFeed: getContractAddress("usdtPriceFeed", true),
      decimals: 18,
      tokenIndex: 3,
      priceDecimals: 8,
      isStrictStable: true,
      tokenWeight: 35000, // 35%
      minProfitBps: 0,
      maxUsdxAmount: 350 * 1000 * 1000,
      // bufferAmount: 60 * 1000 * 1000,
      isStable: true,
      isShortable: false,
    },
    usdc: {
      name: "usdc",
      address: getContractAddress("usdc", true),
      decimals: 18,
      priceFeed: getContractAddress("usdcPriceFeed", true),
      priceDecimals: 8,
      isStrictStable: true,
      tokenWeight: 15000, // 15%
      minProfitBps: 0,
      maxUsdxAmount: 150 * 1000 * 1000,
      // bufferAmount: 60 * 1000 * 1000,
      isStable: true,
      isShortable: false
    },
    matic: {
      name: "matic",
      address: getContractAddress("matic", true),
      priceFeed: getContractAddress("maticPriceFeed", true),
      decimals: 18,
      tokenIndex: 1,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 5000, // 5%
      minProfitBps: 0,
      maxUsdxAmount: 50 * 1000 * 1000,
      // bufferAmount: 15000,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    op: {
      name: "op",
      address: getContractAddress("op", true),
      priceFeed: getContractAddress("opPriceFeed", true),
      decimals: 18,
      tokenIndex: 1,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 5000, // 5%
      minProfitBps: 0,
      maxUsdxAmount: 50 * 1000 * 1000,
      // bufferAmount: 15000,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    arb: {
      name: "arb",
      address: getContractAddress("arb", true),
      priceFeed: getContractAddress("arbPriceFeed", true),
      decimals: 18,
      tokenIndex: 1,
      priceDecimals: 8,
      fastPricePrecision: 1000,
      isStrictStable: false,
      tokenWeight: 5000, // 5%
      minProfitBps: 0,
      maxUsdxAmount: 50 * 1000 * 1000,
      // bufferAmount: 15000,
      isStable: false,
      isShortable: true,
      maxGlobalShortSize: 30 * 1000 * 1000,
    },
    nativeToken: {
      address: getContractAddress("weth"),
      decimals: 18,
      // priceDecimals: 8,
      isStrictStable: false,
    },
  },
};
